apiVersion: v1
kind: Service
metadata:
  name: catalogo-carros-nodeport
  namespace: catalogo-carros
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31222
  selector:
    app: catalogo-carros
