apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: locacar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      nodePort: 30001
