version: "3.9"

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    mem_limit: 2g
    cpus: 0.5
