apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer
  namespace: locacar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - port: 9090
      protocol: TCP
