apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-configmap
  namespace: locacar
data:
  alertmanager.yml: |-
    global:
      slack_api_url: "https://hooks.slack.com/services/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"

    templates:
      - "/etc/alertmanager/template/*.tmpl"

    route:
      group_by: [app, group, env]
      receiver: "ops-locacar"
      group_wait: 15s
      group_interval: 15s
      repeat_interval: 1m

    receivers:
      - name: "ops-locacar"
        slack_configs:
          - channel: "#locacar-api"
            send_resolved: true
            icon_url: https://avatars3.githubusercontent.com/u/3380462
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.app }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end -}}
                )
              {{- end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

              *Summary:* {{ .Annotations.summary }}

              *Description:* {{ .Annotations.description }}

              *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
