apiVersion: v1
kind: Service
metadata:
  name: alertmanager-clusterip
  namespace: catalogo-carros
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
