apiVersion: v1
kind: Service
metadata:
  name: alertmanager-loadbalancer
  namespace: locacar
spec:
  type: LoadBalancer
  selector:
    app: alertmanager
  ports:
    - port: 9093
      protocol: TCP
