apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter-clusterip
  namespace: catalogo-carros
spec:
  type: ClusterIP
  selector:
    app: nginx-prometheus-exporter
  ports:
    - protocol: TCP
      port: 9113
