global:
  scrape_interval: 5s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-locacar:9093

scrape_configs:
  - job_name: "locacar-job"
    metrics_path: /metrics
    static_configs:
      - targets:
          - app-locacar:80

  - job_name: "nginx-job"
    static_configs:
      - targets:
          - nginx-prometheus-exporter-locacar:9113

  - job_name: "netdata-job"
    metrics_path: "/api/v1/allmetrics"
    params:
      format: ["prometheus"]
    scheme: http
    static_configs:
      - targets: ["netdata-locacar:19999"]
