global:
  scrape_interval: 5s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-catalogo-api:9093

scrape_configs:
  - job_name: "app-catalogo-api-job"
    metrics_path: /metrics
    static_configs:
      - targets:
          - app-catalogo-api:80
