apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-configmap
data:
    nginx.conf: |-
        user nginx;
        worker_processes 1;

        error_log /var/log/nginx/error.log warn;
        pid /var/run/nginx.pid;

        events {
            worker_connections 1024;
        }

        http {
            include /etc/nginx/mime.types;
            default_type application/octet-stream;
            access_log off;
            server_tokens off;

            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;

            gzip on;
            gzip_types text/plain text/css application/javascript application/json application/xml;

            server {
                listen 80 default_server;
                listen [::]:80 default_server;
                
                server_name _;
                root /usr/share/nginx/html;

                location /WeatherForecast {
                    proxy_pass http://locacar-clusterip/WeatherForecast;
                }
                
                location /metrics {
                    proxy_pass http://locacar-clusterip/metrics;
                }

                location /metrics-nginx {
                    stub_status;
                }

                location /swagger {
                    proxy_pass http://locacar-clusterip/swagger;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                }            
            }
        }
