apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /var/lib/grafana"]
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      containers:
        - name: grafana-container
          image: grafana/grafana
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "30m"
              memory: 200M
            limits:
              cpu: "60m"
              memory: "400M"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-volumeclaim
        - name: grafana-datasources
          configMap:
            name: grafana-datasource-configmap
