apiVersion: v1
kind: Service
metadata:
  name: catalogo-carros-clusterip
  namespace: catalogo-carros
spec:
  type: ClusterIP
  selector:
    app: catalogo-carros
  ports:
    - protocol: TCP
      port: 80
